try{
    console.log("Executed);
}
catch(error){
    console.log("Error",error);
}